const Header = () => {
  return (
    <div className="font-machina text-foreground">
      <h2 className="text-5xl sm:text-6xl text-center eco-heading pt-10">
        Ecosystem & Treasury
      </h2>
      <div className="flex max-w-3xl mx-auto mt-7 flex-col eco-header-text">
        <p className="max-w-xl self-end">
          GAMESTA Treasury acts as an intermediary between game rewards and the
          player/ NFT holder. Rewards generated by the players' activities are
          sent to the GAMESTA Treasury where they will be converted to $GSG
          tokens
        </p>
        <p className="max-w-md mt-5 text-xs text-end self-end">
          By converting all rewards generated into $GSG tokens, this eliminates
          the need for the players and investors to track each individual's
          tokens whilst also increasing buying pressure on GAMESTA's native
          token. All sources of income generated by GAMESTA
        </p>
      </div>
    </div>
  );
};

export default Header;
